bcgov/nr-ticdi

.github/workflows/main.yml
.github/workflows/pr-open.yml

Updating git workflows as per instructions.

Pipeline: comment out snyk and sonarcloud

---

.openshift-templates/ticdi-nodejs-postgres.yml

Template from https://github.com/openshift/library/blob/master/arch/aarch64/official/nodejs/templates/nodejs-postgresql-persistent.json

Added openshift templates

---

.github/pipeline/deploy.yml
.github/workflows/pr-open.yml
src/app.service.ts

Feature environment setup

---

.github/pipeline/deploy.yml
.github/workflows/pr-close.yml
src/app.service.ts

Feature gui updates

---

.github/workflows/pr-close.yml

Pipeline 3

---

.github/openshift/deploy.backend.yml
.github/openshift/deploy.frontend.yml
.github/workflows/merge-main.yml
.github/workflows/pr-close.yml

Clean up pipeline

---

.github/workflows/_image_promote.yml
.github/workflows/pr-close.yml

Pipeline updates

---

.github/workflows/merge-main.yml
.github/workflows/pr-close.yml

Don't delete pvc since this contains the database

---

.github/workflows/_image_promote.yml

login to container registry

---

.github/openshift/deploy.frontend.yml
frontend/src/app.controller.ts

Integrated keycloak guards

---

backend/src/app.controller.ts
frontend/src/app.controller.ts

Keep database test

---

.github/openshift/deploy.backend.yml
.github/openshift/deploy.frontend.yml
backend/src/app.controller.spec.ts
backend/src/print_request_detail/print_request_detail.service.ts
backend/src/print_request_log/dto/create-print_request_log.dto.ts
backend/src/print_request_log/dto/print_request_log.dto.ts
backend/src/print_request_log/dto/update-print_request_log.dto.ts
backend/src/print_request_log/entities/print_request_log.entity.ts
backend/src/print_request_log/print_request_log.service.ts
frontend/public/js/util.js
frontend/src/admin/admin.controller.ts
frontend/src/admin/admin.module.ts
frontend/src/app.controller.ts
frontend/src/app.module.ts
frontend/src/authentication/authentication.filter.ts
frontend/src/authentication/authentication.service.ts
frontend/src/authentication/generate-report.guard.ts
frontend/src/report/report.controller.ts
frontend/src/report/report.module.ts
frontend/src/ttls/ttls.service.ts
frontend/utils/types.ts
frontend/views/pages/index.hbs

- Add backend test back in for GitHub Actions
- Cleaned up some routes & removed some commented code / unused imports
- Set cookie expiry time equal to the refresh token expiry time
- Add guards to certain routes that should have them
- Redo the collapsibles on the index page
- Store print_request_detail view JSON used to generate documents in print_request_log table as a string
- Always display Land Use Report as an option on the template admin page
- Check for role when generating documents
- Changed how primary contact is obtained
- Updated what's displayed on the page

Many more changes

---

docker-compose.yml
frontend/public/css/custom.css
frontend/public/js/util.js
frontend/src/app.module.ts
frontend/src/main.ts
frontend/src/report/report.controller.ts
frontend/src/ttls/ttls.service.ts
frontend/views/pages/index.hbs
frontend/views/partials/footer.hbs
frontend/views/partials/navbar.hbs

Change the generated report name to use the tenure file number instead of the DTID.
Also:
- Remove the Home link from the navbar
- Add version number to the footer
- Add working docker-compose file
- Fix cookie maxAge being set twice, cookie should have the correct age now
- Add country to Tenure Details

Fix report name

---

backend/src/print_request_detail/dto/create-print_request_detail.dto.ts
backend/src/print_request_detail/dto/print_request_detail.dto.ts
backend/src/print_request_detail/dto/update-print_request_detail.dto.ts
backend/src/print_request_detail/entities/print_request_detail.entity.ts
backend/src/print_request_detail/print_request_detail.service.ts
frontend/src/app.controller.ts
frontend/src/ttls/ttls.service.ts

- Changed the functions that set data to align with the new route
- Added legal_name variable in the print_request_detail db

updates for getting data from new route

---

backend/src/print_request_detail/dto/create-print_request_detail.dto.ts
backend/src/print_request_detail/dto/print_request_detail.dto.ts
backend/src/print_request_detail/dto/update-print_request_detail.dto.ts
backend/src/print_request_detail/entities/print_request_detail.entity.ts
backend/src/print_request_detail/entities/print_request_detail_vw.ts
backend/src/print_request_detail/print_request_detail.service.ts
frontend/src/ttls/ttls.service.ts

Add email address, inspected date, and incorporation number to the print request detail table and view.

Add new variables to print request detail

---

frontend/src/app.controller.ts
frontend/src/ttls/ttls.service.ts
frontend/views/pages/index.hbs

Display the 3 new variables on the index page & format the inspected date slightly

display the 3 new variables

---

frontend/src/app.controller.ts
frontend/src/ttls/ttls.service.ts

Fix the toString on null value issue

quick fix, tested working

---

backend/src/print_request_detail/dto/create-print_request_detail.dto.ts
backend/src/print_request_detail/dto/print_request_detail.dto.ts
backend/src/print_request_detail/dto/update-print_request_detail.dto.ts
backend/src/print_request_detail/entities/print_request_detail.entity.ts
backend/src/print_request_detail/entities/print_request_detail_vw.ts
backend/src/print_request_detail/print_request_detail.service.ts
frontend/src/app.controller.ts
frontend/src/ttls/ttls.service.ts
frontend/views/pages/index.hbs

- Update entities to fit the new document template.
- Add error catch to the index page display.
- Fix issue with primary contact name in header

New doc template updates

---

frontend/public/css/custom.css
frontend/views/pages/index.hbs
frontend/views/partials/navbar.hbs

Move DTID, Tenure File Number, and Primary Contact Name from the navbar to the main section of the page.

move dtid, filenum, contact from navbar to page

---

frontend/src/app.controller.ts
frontend/src/ttls/ttls.service.ts
frontend/views/pages/index.hbs

Format the phone numbers and add the areaCode to the primary contact phone number.

Phone number formatting

---

frontend/views/pages/index.hbs

Other option, display the address lines 1,2,3 on one line.

Display combined address

---

frontend/src/ttls/ttls.service.ts
frontend/views/pages/index.hbs

The phone number will now be formatted in the land use report as well.

format phone number everywhere

---

frontend/src/ttls/ttls.service.ts

remove dash after area code

---

backend/src/main.ts
frontend/public/css/custom.css
frontend/public/js/nfr.js
frontend/src/app.controller.ts

- Added color coding for the provision group dropdown
- Updated LUR/NFR urls

Misc improvements

---

backend/utils/db/init-db.sql
frontend/src/report/report.controller.ts
frontend/src/report/report.service.ts
frontend/utils/util.ts
frontend/views/pages/manage-templates.hbs

- Add fees calculations + formatting
- Change free text edit section to text area
- Update db init script
- Change DB_Name_BCAL_Contact to display the idir user's name
- Update to address variable formatting

New Updates

---

backend/src/nfr_provision/entities/nfr_provision_variable.entity.ts
backend/src/nfr_provision/nfr_provision.controller.ts
backend/src/nfr_provision/nfr_provision.service.ts
frontend/public/js/manage-templates.js
frontend/src/admin/admin.controller.ts
frontend/src/admin/admin.service.ts
frontend/src/ttls/ttls.service.ts
frontend/utils/util.ts
frontend/views/pages/manage-templates.hbs
frontend/views/pages/nfr.hbs

- Can now add/edit/remove variables from provisions
- Updated address formatting
- Updated primary contact display

Variables updates

---

backend/src/document_template/document_template.module.ts
backend/src/document_template/document_template.service.ts
backend/src/nfr_data/entities/nfr_data.entity.ts
backend/src/nfr_data/nfr_data.controller.ts
backend/src/nfr_data/nfr_data.service.ts
backend/src/nfr_provision/nfr_provision.service.ts
frontend/public/js/manage-templates.js
frontend/public/js/nfr.js
frontend/src/app.controller.ts
frontend/src/report/report.controller.ts
frontend/src/report/report.service.ts

- Persist template variants so they aren't deleted every time a user changes the selected variant
- various fixes to activating templates
- bugfix removing To Obtain Survey templates
- fix provision text not being inserted when generating a document

Persist variants

---

backend/src/nfr_provision/nfr_provision.service.ts
frontend/public/js/manage-templates.js

Quick fix that allows users to properly edit variables on the Manage Templates page

the variable id was not being sent to backend

---

frontend/src/report/report.service.ts

gst exempt variable now comes from ticdi endpoint

set gst exempt variable

---

frontend/public/js/nfr.js
frontend/src/report/report.service.ts
frontend/src/ttls/ttls.service.ts

- Disable variable sorting on NFR page as it breaks things
- Add null check for tenantAddr
- Add conditional variables like the showSection variables but for the monies payable section. The only problem with this is that when table rows are hidden, they maintain their height and so you have extra whitespace. I'm sending the updated templates to QA as well.

add some monies payable display logic

---

frontend/src/report/report.service.ts
frontend/src/ttls/ttls.service.ts

Added a bunch of logic for calculating GST differently. The values I get from this updated code line up with the in-depth screenshot shared by Bal so this should be the correct calculation.

add the taxable area calculation on backend

---

frontend/src/report/report.service.ts

- Add back in "<<" regex which disappeared for some reason
- Change how Monies Payable table is filled, looks a lot cleaner and there will be no more gaps.
- Remove the whitespaces from OCC_RENT_DETAILS

More updates

---

frontend/src/report/report.service.ts
frontend/utils/util.ts

Updated the nfrAddressBuilder function to handle multiple parties and combine addresses if they are the same.

display multiple interested parties properly

---

frontend/utils/util.ts

Rewrote the address section to be more readable. The 2nd and 3rd address lines should now be included in the NFR reports

add addrLine2, 3 to address section

---

frontend/utils/util.ts

TICDI-45 - put addrLines on one line

---

backend/src/print_request_log/print_request_log.controller.ts
frontend/src/app.controller.ts

add 2 console logs

---

backend/src/print_request_log/print_request_log.controller.ts
frontend/src/app.controller.ts

update console logs

---

backend/src/nfr_provision/nfr_provision.controller.ts
frontend/src/report/report.controller.ts

more debug logs

---

backend/src/document_template/document_template.controller.ts
frontend/src/app.controller.ts

remove 301's, update if check

---

frontend/src/app.controller.ts

replace dash & endash

---

backend/src/document_template/document_template.controller.ts
frontend/utils/util.ts

After rewriting how the addresses were generated, there was an issue of duplicate addresses being created

Fix duplicate addresses2

---

frontend/src/report/report.service.ts
frontend/src/ttls/ttls.service.ts
frontend/utils/util.ts

- Template now has separate signing lines for each interested party
- Update the mailing addresses to include more information (address lines 1,2,3, city prov country postalCode)

Grazing lease v3

---

frontend/src/app.controller.ts

If a document type was provided, the default page was the Notice of Final Review page. This has been changed back to the land use report page.

change default route back to LUR

---

.prettierrc.json
frontend/src/report/report.service.ts

add prettier config & fix nfr legal desc issue

---

frontend/src/report/report.service.ts

There was an issue with the old search function where it sometimes didn't return the full list of dtid's that have nfr data.

Update report service search function

---

backend/src/document_data_log/document_data_log.service.ts
backend/src/document_data_log/dto/create-document_data_log.dto.ts
backend/src/document_data_log/dto/document_data_log.dto.ts
backend/src/document_data_log/dto/update-document_data_log.dto.ts
backend/src/document_data_log/entities/document_data_log.entity.ts
backend/src/report/report.service.ts

quick fix to entity and related routes

fixing log entity

---

backend/src/admin/admin.controller.ts
backend/src/admin/admin.service.ts
backend/src/document_template/document_template.service.ts
frontend/src/app/common/manage-templates.ts
frontend/src/app/components/modal/manage-templates/EditTemplateModal.tsx
frontend/src/app/components/table/manage-templates/TemplateInfoTable.tsx
frontend/src/app/types/types.ts

Edit template

---

frontend/src/app/content/pages/ManageTemplatesPage.tsx

Bug TICDI-352 fix

---

frontend/src/app/content/pages/ManageDocumentsPage.tsx

removing import which breaks app

---

backend/src/admin/admin.controller.ts
backend/src/authentication/authentication.controller.ts
backend/src/report/report.controller.ts

revert this change once users are assigned roles in test

disable role reqs for now

---

backend/src/admin/admin.controller.ts
backend/src/report/report.controller.ts

uncomment role guards when roles have been given

additional role disabling

---

backend/src/admin/admin.controller.ts
backend/src/app.controller.ts
frontend/src/app/components/table/manage-templates/TemplateInfoTable.tsx
frontend/src/app/content/display/Header.tsx

always display admin navbar link (temporary)

---

backend/src/document_type/document_type.controller.ts
frontend/src/app/common/manage-doc-types.ts
frontend/src/app/components/modal/manage-doc-types/EditProvisionGroupsModal.tsx
frontend/src/app/util/util.ts

- change remove provision group route to post to get around weird 404
- clear error on modal display change
- add debug console log for ttls data retrieval

provision group modal bug fix

---

backend/src/admin/admin.controller.ts
backend/src/report/report.controller.ts
frontend/src/app/content/display/Header.tsx

re-enable role guards for test

reenable role guards

---

backend/src/report/report.service.ts
frontend/src/app/components/common/SimpleSearch.tsx

- fix standard licence db variable not showing
- slight ui adjustment

fix sl address not appearing

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/content/pages/ManageTemplatesPage.tsx
frontend/src/index.tsx

adding react-helmet for csp

---

backend/src/report/report.service.ts
frontend/src/app/App.tsx

- Add assignment assumption report route
- Also update assignment assumption report

add assignment assumption report route

---

backend/src/app.controller.ts

point test environment back to ttls int

---

backend/src/report/report.service.ts
backend/src/util.ts

DB_Address_Street_Tenant - now returns all addresses regardless of addrType
DB_Address_Mailing_Tenant - now returns all addresses regardless of addrType
DB_Tenant_Name - now returns all names regardless of addrType
applies to the new report route as well

update grazing lease variables

---

frontend/src/app/content/display/Provisions.tsx
frontend/src/app/content/pages/LandingPage.tsx

- Add group max text
- Add simple licence / lease filter

Ticdi 363 365

---

frontend/src/app/components/modal/manage-provisions/EditProvisionModal.tsx
frontend/src/app/components/modal/manage-provisions/RemoveProvisionModal.tsx
frontend/src/app/components/modal/manage-provisions/forms/EditProvisionModalForm.tsx
frontend/src/app/util/util.ts

- Fix primary contact name issue not displaying legal name when no first/middle/last name aren't available
- Fix Edit Provision modal state on close

Ticdi 360 362

---

frontend/src/app/content/pages/LandingPage.tsx

doc type wasn't clearing on search

clear data on dtid search

---

backend/src/report/report.service.ts
frontend/src/app/components/modal/manage-doc-types/AddDocTypeModal.tsx
frontend/src/app/components/table/manage-templates/TemplateInfoTable.tsx
frontend/src/app/components/table/reports/SelectedProvisionsTable.tsx
frontend/src/app/content/display/TenureDetails.tsx
frontend/src/app/content/pages/LandingPage.tsx
frontend/src/app/content/pages/ManageDocumentsPage.tsx

Tickets: 71, 74, 75, 78, 83
Template tickets (no code changes): 76, 79, 82

Ticdi updates

---

backend/src/provision/dto/create-provision.dto.ts
backend/src/provision/dto/provision.dto.ts
backend/src/provision/dto/update-provision.dto.ts
backend/src/provision/entities/provision.entity.ts
backend/src/provision/provision.controller.ts
backend/src/provision/provision.service.ts
backend/src/report/report.service.ts
backend/src/types.ts
frontend/src/app/components/modal/manage-provisions/AddProvisionModal.tsx
frontend/src/app/components/modal/manage-provisions/forms/EditProvisionModalForm.tsx
frontend/src/app/components/table/manage-provisions/ManageProvisionsTable.tsx
frontend/src/app/content/pages/LandingPage.tsx
frontend/src/app/content/pages/ManageProvisionsPage.tsx
frontend/src/app/types/api-request-parameters.ts
frontend/src/app/types/types.ts
migrations/sql/V1.0.20__provision_list.sql

- Add list option for provisions
- Add list_items (string array) and list_enabled (boolean) to provision table
- Provisions can be toggled between free text and list.

Ticdi 81 provision list

---

frontend/src/app/components/modal/manage-provisions/AddProvisionModal.tsx
frontend/src/app/components/modal/manage-provisions/forms/EditProvisionModalForm.tsx

- fix issue with add provision modal clearing

TICDI-81 - update fixing add provision modal not clearing

---

frontend/src/app/components/modal/manage-provisions/forms/EditProvisionModalForm.tsx

- Free Text textarea had no default value, add default value

set free_text default value

---

backend/src/provision/dto/create-provision.dto.ts
backend/src/provision/dto/provision.dto.ts
backend/src/provision/dto/update-provision.dto.ts
backend/src/provision/entities/provision.entity.ts
backend/src/provision/provision.controller.ts
backend/src/provision/provision.service.ts
backend/src/report/report.service.ts
backend/src/types.ts
frontend/src/app/components/modal/manage-provisions/AddProvisionModal.tsx
frontend/src/app/components/modal/manage-provisions/forms/EditProvisionModalForm.tsx
frontend/src/app/content/pages/LandingPage.tsx
frontend/src/app/types/types.ts
migrations/sql/V1.0.21__provision_list_update.sql

- Remove list toggle, list is always present in a provision.

make list separate from free text

---

backend/src/report/report.controller.ts

- Quick fix for the IDIR name in reports

DB_NAME_BCAL_CONTACT fix

---

backend/src/admin/admin.service.ts
backend/src/enum/role.enum.ts

- No longer add/remove generate documents role when creating/removing admin users

remove gen reports role

---

charts/app/values.yaml

fix/update replicas Update values.yaml
