- backend/src/print_request_detail/dto/create-print_request_detail.dto.ts
- backend/src/print_request_detail/dto/print_request_detail.dto.ts
- backend/src/print_request_detail/dto/update-print_request_detail.dto.ts
- backend/src/print_request_detail/print_request_detail.service.ts
- frontend/src/app.controller.ts
- frontend/src/ttls/ttls.service.ts
- Set the licence holder name to legal name if no first/middle/last name exist (this was happening on the frontend already but not in the database)
- Fix an issue with displaying the area section.
- Move mailing address + licence holder name parsing to ttlsService
> Licence holder name + area display fixes

- frontend/src/authentication/generate-report.guard.ts
For now, return true in the guard instead of checking for the proper role.
> disable docgen guard

- frontend/src/report/report.controller.ts
- frontend/src/ttls/ttls.service.ts
Tenure File Number was sometimes being treated as a number causing it to lose leading 0's, treat it as a string in all cases now.
The Contact Agent variable was set to just use the first name and middle name of the contact, added the last name as well.
> treat tfn as string, update contact name

- frontend/src/authentication/generate-report.guard.ts
The GenerateReportGuard was checking that client_roles was not null before allowing the report to be generated.
> allow client_roles to be null and still generate report

- backend/src/nfr_data/nfr_data.service.ts
- backend/src/nfr_provision/dto/create-nfr_provision.dto.ts
- backend/src/nfr_provision/dto/nfr_provision.dto.ts
- backend/src/nfr_provision/dto/update-nfr_provision.dto.ts
- backend/src/nfr_provision/entities/nfr_provision.entity.ts
- backend/src/nfr_provision/nfr_provision.controller.ts
- backend/src/nfr_provision/nfr_provision.service.ts
- frontend/public/css/custom.css
- frontend/public/js/manage-templates.js
- frontend/public/js/nfr.js
- frontend/src/admin/admin.controller.ts
- frontend/src/admin/admin.service.ts
- frontend/src/app.controller.ts
- frontend/src/main.ts
- frontend/src/report/report.controller.ts
- frontend/src/report/report.service.ts
- frontend/views/pages/manage-templates.hbs
- frontend/views/pages/nfr.hbs
- frontend/views/pages/search.hbs
- Updated the add/edit routes for NFR provisions
- You can now select which variants have access to that provision.
- Added Help Text field to add/edit provision modal.
- Added Mandatory Provision option to add/edit provision modal (mandatory provision status does nothing right now).
- Updated NFR page
- Added Select option to group dropdown
- Disabled Mandatory provision logic, provisions/variables will no longer be preloaded unless they were previously saved for that DTID.
- Updated Search
- Made accessible by regular users
- Fixed the Open button sending users to a 404 page
> updating the manage-templates page

- frontend/public/js/nfr.js
The provision group select repopulates after changing the variant type, the Select option wasn't being added in this situation.
> quick fix to provision group select

- backend/utils/db/init-db.sql
- frontend/public/css/custom.css
- frontend/public/js/manage-templates.js
- frontend/public/js/nfr.js
- frontend/src/app.controller.ts
- frontend/src/report/report.service.ts
- frontend/views/pages/manage-templates.hbs
- frontend/views/pages/nfr.hbs
- Group Select maximum text change
- Address on NFR page display change
- Added Mandatory provision logic & table column, user can no longer generate a document if all mandatory provisions have not been selected.
- Added the option for groups to have no maximum and updated frontend for that change
- Variable 'Value' column header changed to 'Enter Text'
- Interested parties now populates from tenantAddr array, it seems that there will either be a legalname or a first/middle/last but not both so the way interested parties are displayed should probably change.
> More changes

- frontend/src/report/report.service.ts
Added code to add line breaks to the ends of existing provisions and certain variables instead of having them on the template inside showBegin/showEnd blocks.
> report whitespace workaround

- frontend/src/report/report.service.ts
- frontend/utils/util.ts
Added regex to check all provision.free_text and variable values for the character "«" and to update that string to something that the cdogs templating logic will understand.
«DB_TENURE_TYPE» would become {d.DB_Tenure_Type} and «VAR_TELEPHONE_NUMBER» would become {d.VAR_Telephone_Number}
In order to insert values for these nested variables, cdogs gets run a second time.
> TICDI-24 nested values

- frontend/src/report/report.service.ts
Documentation Amount is used in the GST calculations and if present it will be displayed in the Monies Payable table.
> Added Documentation Fee back in

- frontend/utils/util.ts
If an interested party exists twice (same name + address) then only display it once in the frontend.
> remove duplicate ips in frontend webpage

- frontend/public/js/util.js
- frontend/src/app.controller.ts
- frontend/src/report/report.service.ts
- frontend/utils/util.ts
- frontend/views/pages/grazing-lease.hbs
- The Grazing Lease page now displays the same data that the Notice of Final Review page does
- Updated address generation for the Grazing Lease document
> Gl page updates

- backend/src/document_data/document_data.controller.ts
- frontend/src/app/common/report.ts
- frontend/src/app/content/pages/LandingPage.tsx
> Landing Page clear button

- backend/src/report/report.service.ts
- migrations/sql/V1.0.16__ticdi_add_new_provisions.sql
- Add Standard Licence provisions and variables to database
- Add Assignment Assumption provisions and variables to database
> Slpl aapl provs and vars

- frontend/src/app/components/common/Collapsible.tsx
- frontend/src/app/content/pages/IndexPage.tsx
- frontend/src/app/content/pages/LandingPage.tsx
- Will now open collapsibles properly on retrieve
> collapsible will open on retrieve now

- frontend/src/app/components/table/manage-doc-types/EditDocTypeTable.tsx
- frontend/src/app/components/table/manage-doc-types/ManageDocumentProvisionsTable.tsx
- frontend/src/app/content/pages/ManageDocumentsPage.tsx
Initial Save Provision simply saved the entire list of DocTypeProvisions, with hundreds of provisions this was causing issues.
Save will now only the updated provisions.
> saving provisions was inefficient and failing

- backend/src/provision/provision.service.ts
- backend/src/types.ts
- frontend/src/app/App.css
- frontend/src/app/common/manage-doc-types.ts
- frontend/src/app/components/modal/manage-doc-types/GlobalProvisionModal.tsx
- frontend/src/app/components/table/manage-doc-types/ManageDocumentProvisionsTable.tsx
- frontend/src/app/components/table/manage-provisions/ManageProvisionsTable.tsx
- frontend/src/app/content/pages/ManageDocumentsPage.tsx
- frontend/src/app/types/types.ts
- Change Manage Document Types table to display global provision id instead of document type provision id
- Add modal that contains respective global provision information when clicking provision id on Manage Document Types page
> ticdi-364 changes

- frontend/src/app/components/table/manage-doc-types/ManageDocumentProvisionsTable2.tsx
- frontend/src/app/content/pages/ManageDocumentsPage.tsx
Quick PR to remove a database call and to align the Manage Document Type Provisions table headers
> remove global provisions call, align table headers

- frontend/src/app/common/api.ts
- Fix issue where no JWT was being sent to the backend
> always require jwt auth

- backend/src/report/report.service.ts
- frontend/src/app/components/common/Collapsible.tsx
- frontend/src/app/content/pages/LandingPage.tsx
- frontend/src/app/content/pages/ManageProvisionsPage.tsx
- Adjust create document page display
- Add ID to global provision search
- Update backend cdogs error logging
> Ticdi 103 - create document page layout

- backend/src/admin/admin.controller.ts
- backend/src/admin/admin.service.ts
- frontend/src/app/common/manage-admins.ts
- frontend/src/app/components/modal/manage-admins/AddAdmin.tsx
- frontend/src/app/components/modal/manage-admins/RemoveAdmin.tsx
- Update CSS admin role logic to handle MFA logins as well as regular logins
> TICDI-99 - Handle roles for IDIR - MFA logins

- frontend/public/css/new.css
- frontend/src/app/components/common/Collapsible.tsx
- frontend/src/app/components/modal/manage-provisions/AddProvisionModal.tsx
- frontend/src/app/components/modal/manage-provisions/forms/EditProvisionModalForm.tsx
- frontend/src/app/content/pages/LandingPage.tsx
- Small usability fix for List Enabled checkbox
- Styling changes for TICDI-103
> TICDI-81 checkbox update + TICDI-103 styling changes

- backend/src/admin/admin.module.ts
- backend/src/admin/admin.service.ts
- backend/src/document_data/document_data.service.ts
- backend/src/document_template/document_template.service.ts
- backend/src/document_type/document_type.service.ts
- Delete provision groups, templates, and document data when deleting a document type.
> delete all data related to doc type on deletion

- backend/src/report/report.service.ts
- frontend/src/app/content/pages/LandingPage.tsx
- Null provision group for mandatory provision wasn't being handled properly on the generate document page
- Tenure object in LUR report was being stringified, this previously worked but now it doesn't. Removing the string conversion fixed the issue
> TICDI-117/118
